config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  devise_for :admin
  resources :admin_only
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
    resources :reviews
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :user
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :user
  has_many :reviews

  validates :name, :maker, :location, :year, presence: true

  # mount_uploader :wine_photo, WinePhotoUploader

  def self.search(search)
    where("name ILIKE ? OR maker ILIKE ? OR location ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
  end

end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :user 
  belongs_to :product

  validates :title, :body, presence: true

end

app/models/user.rb
class User < ApplicationRecord

  validates :first_name, :last_name, :email, :username, :password, :password_confirmation,
    presence: true
  validates :email, format: {with: /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   def admin?
     role == "admin"
   end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authorize_admin!

  def index
    @users = User.all
  end

  private

  def authorize_admin!
    if !user_signed_in? || !current_user.admin?
      redirect_to new_admin_session_path, notice: "Please Login as Admin to view that page!"
    end
  end
end

app/controllers/api/v1/voting_controller.rb
class Api::V1::VotingController < ApiController

  def create
    review = Review.find(params[:id])
    up_vote = review.increment!(:votes_count)

    render json: up_vote, status: 422
  end

  def destroy
    review = Review.find(params[:id])
    down_vote = review.destroy

    render json: down_vote
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  skip_before_action :verify_authenticity_token
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception

   def after_sign_in_path_for(users)
     root_path
   end

 before_action :configure_permitted_parameters, if: :devise_controller?

   def after_sign_out_path_for(users)
     root_path
   end

 protected

   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :username])
   end

end

app/controllers/product_reviews_controller.rb
class ProductReviewsController < ApplicationController
  before_action :authenticate_user!
  def index
    @wine = Product.find(params[:product_id])
    @reviews = @product.reviews
  end

  def new
    @wine = Product.find(params[:product_id])
    @review = Review.new
  end

  def create
    @wine = Product.find(params[:product_id])
    @review = Review.new(review_params)
    @review.wine = @wine

    if @review.save
      flash[:notice] = "Review saved successfully."
      redirect_to product_path(@wine)
    else
      flash[:alert] = "Failed to save review."
      render :new
    end
  end

  private

    def authenticate_user!
      if user_signed_in?
        super
      else
        redirect_to new_user_session_path, notice: "Please Login to view that page!"
      end
    end

    def review_params
      params.require(:review).permit(:body)
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @wines = Product.all
    if params[:search]
      @wines = Product.search(params[:search]).order("created_at DESC")
    else
      @wines = Product.all.order("created_at DESC")
    end
  end

  def show
    @wine = Product.find(params[:id])
    @reviews = @wine.reviews
  end

  def new
    @wine = Product.new
  end

  def create
    @wine = Product.new(wine_params)
    if @wine.save
      redirect_to @wine
      flash[:success] = "Wine added!"
    else
      flash[:notice] = "Error. All forms must be valid. Please edit and try again."
      render :new
    end
  end

  def edit
    @wine = Product.find(params[:id])
  end

  def update
    @wine = Product.find(params[:id])
    @wine.update(wine_params)
    flash[:success] = "Wine saved!"
    redirect_to @wine
  end

  def destroy
    @wine = Product.find(params[:id])
    @wine.destroy
    flash[:success] = "Wine has been removed."
    redirect_to products_path
  end

  private

    def authorize_user!
      if !user_signed_in? || !current_user.admin?
        redirect_to new_user_session_path, notice: "Please Login to view that page!"
      end
    end

    def wine_params
      params.require(:product).permit(:name, :maker, :location, :year).merge(user: current_user)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def index
    @wine = Product.find(params[:product_id])
    @reviews = @wine.product
  end

  def new
    @wine = Product.find(params[:product_id])
    @review = Review.new
  end

  def create
    @wine = Product.find(params[:product_id])
    @review = Review.new(review_params)
    @review.product = @wine

    if @review.save
      flash[:notice] = "Review saved successfully."
      redirect_to product_path(@wine)
    else
      flash[:alert] = "Failed to save review."
      render :new
    end
  end

  def edit
    @wine = Product.find(params[:product_id])
    @review = @wine.reviews.find(params[:id])
  end

  def update
    @wine = Product.find(params[:product_id])
    @review = @wine.reviews.find(params[:id])
    @review.update_attributes(review_params)
    if @review.save
      flash[:success] = "Review saved!"
      redirect_to product_path(@wine)
    else
      flash[:alert] = "All forms must be valid."
      render :edit
    end
  end

  def destroy
    @wine = Product.find(params[:product_id])
    @review = @wine.reviews.find(params[:id])
    @review.destroy
    flash[:success] = "Review deleted."
    redirect_to product_path(@wine)
  end

  private

    def authorize_user!
      if !user_signed_in? || !current_user.admin?
        redirect_to new_user_session_path, notice: "Please Login to view that page!"
      end
    end

    def review_params
      params.require(:review).permit(:title, :body).merge(user: current_user)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<h1> Administrator Dashboard</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gary V Wine Reviews</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <h1>Gary V Wine Reviews</h1>
    <br>
    <nav>
      <% if user_signed_in? %>
        <%= link_to 'Add A Wine', new_product_path %>
        <%= link_to 'My Account', edit_user_registration_path %>
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
        <% if current_user.admin? %>
          <li><%= link_to "Admin Section", admin_only_index_path %></li>
        <% end %>
      <% else %>
        <%= link_to 'Sign Up', new_user_registration_path %>
        <%= link_to 'Sign In', new_user_session_path %>
      <% end %>
    </nav>
    <br>
    <%= form_tag(products_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Wines", required: true  %>
        <%= submit_tag "Search", :name => nil %>
    <% end %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/helpful.html.erb
<section>
  <h2>You Found This Review Helpful!</h2>
</section>

app/views/product_reviews/new.html.erb
<h2> Write Your Review Below For <%= @product.name %> </h2>
<%= form_for [@product, @review] do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit 'Add Review' %>
  </div>

<% end %>
<br>
<hr>

app/views/products/edit.html.erb
<h2>Edit Your Wine Below</h2>
<%= form_for @wine do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :maker %><br />
    <%= f.text_field :maker %>
  </div>
  <br>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <br>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit 'Save Wine' %>
  </div>

<% end %>
<br>
<hr>
<p>Go Back To<%= link_to, 'Home Page', root_path %></p>

app/views/products/index.html.erb
<h2>Wine List</h2>
<hr>
<ul>
  <% @wines.each do |wine| %>
    <li> <%= link_to wine.name, product_path(wine) %> </li>
    <p>By: <%= wine.maker %> </p>
    <h5>Click Name For More Info And Reviews</h5>
    <hr>
  <% end %>
</ul>

app/views/products/new.html.erb
<h2>Add Your Wine Below</h2>
<%= form_for @wine do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :maker %><br />
    <%= f.text_field :maker %>
  </div>
  <br>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <br>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit 'Add Wine' %>
  </div>

<% end %>
<br>
<hr>
<p>Go Back To<%= link_to, 'Home Page', root_path %></p>

app/views/products/show.html.erb
<nav>
  <% if current_user.id == Product.find(params[:id]).user_id || current_user.admin? %>
    <%= link_to 'Edit Wine', edit_product_path %>
    <%= link_to 'Delete Wine',  @wine, method: :delete %>
    <%= link_to 'Add A Wine', new_product_path %>
    <%= link_to 'My Account', edit_user_registration_path %>
    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
    <% if current_user.admin? %>
      <li><%= link_to "Admin Section", admin_only_index_path %></li>
    <% end %>
  <% else %>
    <%= link_to 'Add A Wine', new_product_path %>
    <%= link_to 'My Account', edit_user_registration_path %>
    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
  <% end %>
</nav>

<h1><%= @wine.name %></h1>
<ul>
  <li><b>Made By: </b> <%= @wine.maker %> </li>
  <li><b>From: </b> <%= @wine.location %> </li>
  <li><b>Year Made: </b> <%= @wine.year %> </li>
</ul>
<hr>
<nav>
  <%= link_to 'Add Review', new_product_review_path(@wine) %>
</nav>
<br>
<%= render partial: "reviews/index", collection: @reviews %>
<br>

app/views/reviews/_index.html.erb
<h2> Reviews </h2>
<% @reviews.each do |review| %>
  <%= review.title %>
  <%= review.body %>
  <p><b>Review By: </b> <%= review.user.username %> </p>
  <% if current_user.id == review.user.id || current_user.admin? %>
    <%= link_to 'Edit Review', edit_product_review_path(@wine, review) %>
  <% end %>
  <hr>
<% end %>

app/views/reviews/edit.html.erb
<h2> Edit Your Review Below </h2>
<%= form_for [@wine, @review] do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <br>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit 'Save Review' %>
  </div>

<% end %>
<br>
<hr>
<h4>You can delete your review here</h4>
<%= link_to 'Delete Review', [@wine, @review], method: :delete %>
<br>
<p>Go Back To<%= link_to, 'Home Page', root_path %></p>

app/views/reviews/new.html.erb
<h2> Write Your Review Below </h2>
<%= form_for [@wine, @review] do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <br>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit 'Add Review' %>
  </div>

<% end %>
<br>
<hr>
<br>
<p>Go Back To<%= link_to, 'Home Page', root_path %></p>